### PR TITLE
EventQueue fixes

### LINKED ISSUE #154: Chore: eventloop/queue implementation has some weirdness
We do this:
```go
if len(q.entries) == 0 {
	panic("cannot push to a queue with capacity 0")
}
```
in the `push` method? Moreover, this is not how to check the capacity of a slice.

If we want to check the `capacity` of the slice, we should do it when constructing the queue, using the input `capacity` argument, not after it has been created. This would be how you check the capacity of a slice, if needed:
```go
if cap(q.entries) == 0 {
	panic("cannot push to a queue with capacity 0")
}
```
If the idea was to check the `length` of the slice, then why can't you push to an empty queue with (presumably some) capacity?

### PR DESCRIPTION
**Pull request by AlanRostem**
Fixes #154 

This PR improves the documentation of the event queue implementation, fixes an invalid check, and adds a warning log when the event queue is full.

All tests pass and things run as intended. Though it would be nice open an issue for stress testing the event queue further.

### CODE REVIEW

File: eventloop/queue.go [hunk 1]
```diff
@@ -21,13 +25,13 @@ func newQueue(capacity uint) queue {
 	}
 }
 
-func (q *queue) push(entry any) {
+// push adds an entry to the buffer in a FIFO fashion. If the queue is full, the first
+// entry is dropped to make space for the newest entry and returns true.
+func (q *queue) push(entry any) (droppedOne bool) {
```
Comment (meling) [inline eventloop/queue.go:30]: What if we instead return the dropped event; then we can log the event that was dropped. See implementation below.
```go
func (q *queue) push(entry any) (droppedEvent any) {
...
		droppedEvent = q.entries[q.head] // Line 46 with current: dropped = true
...
	return droppedEvent
```

File: eventloop/eventloop.go [hunk 2]
```diff
@@ -129,7 +137,10 @@ func (el *EventLoop) AddEvent(event any) {
 	if event != nil {
 		// run handlers with runInAddEvent option
 		el.processEvent(event, true)
-		el.eventQ.push(event)
+		dropped := el.eventQ.push(event)
```
Comment (meling) [inline eventloop/eventloop.go:140]: See details below...
```go
droppedEvent := el.eventQ.push(event)
if droppedEvent != nil {
	el.logger.Warnf("event queue is full, dropped event: %v", droppedEvent)
}
```

**Review by meling — APPROVED** [review]
