### PR TITLE
Simplify config handling and other fixes to orchestration

### LINKED ISSUE #168: Simplify the configuration handling code
The current way the config is handled is very complex for handling both cli/viper and Cue, and difficult to maintain compatibility between them.

I suggest putting all possible config parameters in the `HostConfig` from https://github.com/relab/hotstuff/blob/master/internal/config/config.go

...and implement two constructor variants for this struct:

1. `NewFromViper() *HostConfig`
2. `NewFromCue(filepath string) *HostConfig`

Variant 1 creates the struct using `viper.Get()`-like calls to supply the values to the struct. We use this variant when the `--cue` flag is empty.

Otherwise, when a Cue file is specified, variant 2 is used. This means the `schema.cue` file must support default values like the way Viper is set up now. 

I believe this approach simplifies things a lot and the way configs are handled for both formats will be the same code and decoupled.

### PR DESCRIPTION
**Pull request by AlanRostem**
Fixes #168

Previously, the `--hosts` cli flag was omitted when integrating Cue. Now I have introduced `--client-hosts` and `--replica-hosts` to the cli so that things can work like before and be compatible with Cue if the user chooses to. 

Both Cue and Viper (.toml) are compatible with the framework. 

The code has also been adapted to support the following:

- Multiple config formats
- One standardized `ExperimentConfig` struct that holds all possible parameters
- Simpler code for experiment/test setup, independent of config format
- CLI flags, `.toml`, and `.cue` configs can work in tandem

This PR also solves #150, #159, and #174

### CODE REVIEW

File: internal/cli/run.go [hunk 1]
```diff
@@ -149,81 +47,47 @@ func runController() {
...
 	checkf("failed to connect to remote hosts: %v", err)
 
-	if exePath == "" {
-		exePath, err = os.Executable()
+	if cfg.Exe == "" {
+		cfg.Exe, err = os.Executable()
 		checkf("failed to get executable path: %v", err)
 	}
 
+	// TODO: Generate DeployConfig from ExperimentConfig type.
```
Comment (meling) [inline internal/cli/run.go:58]: There is a circular dependency if you move the logic to the config package, since `orchestration/controller.go` uses `config.ExperimentConfig` and more from `config`... We should perhaps rethink if we can structure things a bit better between the packages.

File: internal/orchestration/controller.go [hunk 2]
```diff
@@ -153,7 +141,7 @@ func (e *Experiment) createReplicas(replicaMap config.ReplicaMap) (cfg *orchestr
 			if err != nil {
 				return nil, err
 			}
-			opt.SetTreeOptions(e.hostCfg.BranchFactor, e.hostCfg.TreePositions, e.hostCfg.TreeDelta)
+			// opt.SetTreeOptions(e.hostCfg.BranchFactor, e.hostCfg.TreePositions, e.hostCfg.TreeDelta)
```
Comment (meling) [inline internal/orchestration/controller.go:144]: Keep or drop?

File: internal/orchestration/orchestration_test.go [hunk 3]
```diff
@@ -11,176 +11,150 @@ import (
...
-		}()
+func run(t *testing.T, cfg *config.ExperimentConfig) {
+	t.Helper()
 
-		err = experiment.Run()
-		if err != nil {
-			t.Fatal(err)
-		}
+	controllerStream, workerStream := net.Pipe()
+	workerProxy := orchestration.NewRemoteWorker(protostream.NewWriter(controllerStream), protostream.NewReader(controllerStream))
```
Comment (meling) [inline internal/orchestration/orchestration_test.go:78]: I got curious about this line and the next one; we use `controllerStream` in both on the same line, and `workerStream` in both on the next line. Does this make sense?
Looking at code from `cli/run.go`:
```go
		remoteWorkers[host] = orchestration.NewRemoteWorker(
			protostream.NewWriter(session.Stdin()), protostream.NewReader(session.Stdout()),
		)
```
We use a different stream for the reader and writer.

**Review by meling — CHANGES_REQUESTED** [review]

File: internal/orchestration/controller.go (hunk 2 above)
Comment (AlanRostem) [reply internal/orchestration/controller.go:144]: This can be droppped since the values are set from `CreateReplicaOpts` in `ExperimentConfig`.

File: internal/cli/run.go [hunk 4]
```diff
@@ -14,132 +13,31 @@ import (
...
-		cfg.TreeDelta = viper.GetDuration("tree-delta")
+	cuePath := viper.GetString("cue")
+	if cuePath != "" {
+		cfg, err = config.NewCue(cuePath, cfg)
+		checkf("config error when loading %s: %v", cuePath, err)
 	}
 
-	worker := viper.GetBool("worker")
+	// A cleaner way would be to have this in the constructor of
+	// config, but this is done here since the Cue might overwrite
```
[the remark this answers is not in the document]
Comment (AlanRostem) [reply internal/cli/run.go:35]: The above comment refers to both, but then you'd have to duplicate the code for both constructors, which is why I added the comment. An even cleaner approach would be to create a `type TreePositions []uint32` and add a `Randomize()` method to it.

[the remark this answers is not in the document]
Comment (AlanRostem) [reply internal/cli/run.go:35]: I agree with the "order of magnitude". I will open a separate issue/PR on this

File: internal/cli/run.go (hunk 1 above)
Comment (AlanRostem) [reply internal/cli/run.go:58]: Agreed. Perhaps a PR on #172 could contribute to this

**Review by meling — APPROVED** [review]
